name: korean-lm
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - transformers
  - datasets
  - pandas
  - matplotlib
  - scikit-learn
  - jupyter
  - tqdm
  - pip
  - pip:
      - googletrans==4.0.0-rc1
